language: node_js
node_js:
- 6
deploy:
  provider: heroku
  app: frontend2016
  api_key:
    secure: LjCsYDeJOblfwnACY/0I5MRIzbbrKxfbltbs2zMvGyN6nRJxx4oY4pvl+a6bFQey2Yx5Or3zP24PHRbD2ZRhG4WtrEnCbgeHI67TWH3Ya8iJ/EOfFFvKVC2knC1bSjTMojxY5UjvfV+c1YbLy8PI5MTTW/MjxkwP9fJEFtwIxmdri14i0gipk52kgrsWoI4s+dUevgf253uV7XeyMkjYgoZv6DPIw56ahqKqdkHcAQa+yqqVB7yR9xMQSWW/SuoyPz3woXnaWDJ/CPARz3FyfcZ0tCsjuVYHtPoBCf1FJZqky+8MTSzlLHpH2NgRM6zON9dhl6HYWw0Ivpbn5SC2+ggCQpn96/ecTLqFKo2PUmt8z4KuUyrLQo3CjeG/gTOPPUHT1cXq7mnRLrj4cyf+ZYwf2wgQG8M8BlcmTMmBDrD+1UGnivbLKO7DelbSVrQTJ9CV7Mf3Sv/xpCl+Ze6X9KHeQuvyWbUUPMwrsLRd7rR/3XWAHbVe8OWQgkxbhsmKDpqqNOwevBemlRG8Ejn6vv220awMz93paVHsIEQ04crlW5sBf9xf8wrJn4sQR9LsTJKcS0/RdxvI4qqk2V1tRqMbID/ZBAlE1Nu5YCRhAYa97Unv1Xq+jzAmjKkJNW6sbVh7h3LEByvQdLj2vwsPFw/40EsOHTLhHMXJNJUvLxs=
