language: node_js
node_js:
- 6
deploy:
  provider: heroku
  app: frontend2016
  api_key:
    secure: acaA2sLtB5NX+DqcTkmN5vzj/jk61H78ASCuBadJ79fsDkHE9es9qBBOyUJ/35jq4T0i4jLi65gIFcWn9zPiHIhYlC69OQ1Lrtu3qW8cQ82/2Tv4qwMa+upkTofpTjbI2calVN1H0xUQxa0k31xD6XJSQLd0Rw2Paafg6IcZE57CuR9xj5/AGL40FVsiVE+4ZOw6+LIW+A2dFnjm8zHvjqAyVo8wmsM9yrIatFPFafkbF65KclnCnMAiv96zFZY7B8NmSEcevLjAnQuBa8IEmojh1IssJNztj8fOWDwWw+Ur/PLN20iiKpX5UlJHZpfH6HEz2u2CHHOhvDH/+IU3cC6ukrC3ncRZ1cYl398XNTlfqahNuuMFXUvR81+einI/Xtst/Squ4kdVyxMuj7Uub6HlRUubXWdB4iLrfDCMmk0mUfakSAcRIAzr0bso1hvR91r4cvc+UNdnnfO6hA5ucDtAmOyJIXFOIoIaxzClxPAEZOMivDkWKTMUUE4Cf6WF2tJaMvKrz/lWnag7LBos2DGbTCNR9AbX31o4eQ3kUhRLenB4bOXDlt3GOFSbZHvOThSo3ZoC+RM20mcrbD6UhToTOj0WrHxhDHGN82Hi6xWDlt0wtWnCJvEnT2JQBRgUn4GGOjXeiZm+R1Z0/CmzEj+dtvfRHAMnHEXw2kPTIXY=
  on:
    all_branches: true
